import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  BadRequestException,
  UnauthorizedException,
  NotFoundException,
  ForbiddenException,
  NotAcceptableException,
  RequestTimeoutException,
  ConflictException,
  GoneException,
  HttpVersionNotSupportedException,
  PayloadTooLargeException,
  UnsupportedMediaTypeException,
  UnprocessableEntityException,
  InternalServerErrorException,
  NotImplementedException,
  ImATeapotException,
  MethodNotAllowedException,
  BadGatewayException,
  ServiceUnavailableException,
  GatewayTimeoutException,
  PreconditionFailedException,
  HttpStatus,
} from '@nestjs/common';
export const httpStatusesByException = new Map<any, HttpStatus>([
  [BadRequestException, HttpStatus.BAD_REQUEST],
  [UnauthorizedException, HttpStatus.UNAUTHORIZED],
  [NotFoundException, HttpStatus.NOT_FOUND],
  [ForbiddenException, HttpStatus.FORBIDDEN],
  [NotAcceptableException, HttpStatus.NOT_ACCEPTABLE],
  [RequestTimeoutException, HttpStatus.REQUEST_TIMEOUT],
  [ConflictException, HttpStatus.CONFLICT],
  [GoneException, HttpStatus.GONE],
  [HttpVersionNotSupportedException, HttpStatus.HTTP_VERSION_NOT_SUPPORTED],
  [PayloadTooLargeException, HttpStatus.PAYLOAD_TOO_LARGE],
  [UnsupportedMediaTypeException, HttpStatus.UNSUPPORTED_MEDIA_TYPE],
  [UnprocessableEntityException, HttpStatus.UNPROCESSABLE_ENTITY],
  [InternalServerErrorException, HttpStatus.INTERNAL_SERVER_ERROR],
  [NotImplementedException, HttpStatus.NOT_IMPLEMENTED],
  [ImATeapotException, HttpStatus.I_AM_A_TEAPOT],
  [MethodNotAllowedException, HttpStatus.METHOD_NOT_ALLOWED],
  [BadGatewayException, HttpStatus.BAD_GATEWAY],
  [ServiceUnavailableException, HttpStatus.SERVICE_UNAVAILABLE],
  [GatewayTimeoutException, HttpStatus.GATEWAY_TIMEOUT],
  [PreconditionFailedException, HttpStatus.PRECONDITION_FAILED],
]);

export const exceptionMessages = new Map<any, string>([
  [BadRequestException, 'Ops, något gick fel.'],
  [UnauthorizedException, 'Saknas behörighet vänligen logga in.'],
  [NotFoundException, 'Kunde inte hitta resursen.'],
  [ForbiddenException, 'Du saknar tillåtelse att utföra.'],
]);
